services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nonogram-app
    ports:
      - "3000:3000"
    volumes:
      - nonogram_data:/app/data
    restart: unless-stopped

volumes:
  nonogram_data: